# Copyright 2016 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# copy from ${grpc_source_dir}/BUILD

set(libgrpc_unsecure_source_files
	${grpc_source_dir}/src/core/profiling/timers.h
	${grpc_source_dir}/src/core/support/block_annotate.h
	${grpc_source_dir}/src/core/support/env.h
	${grpc_source_dir}/src/core/support/file.h
	${grpc_source_dir}/src/core/support/murmur_hash.h
	${grpc_source_dir}/src/core/support/stack_lockfree.h
	${grpc_source_dir}/src/core/support/string.h
	${grpc_source_dir}/src/core/support/string_win32.h
	${grpc_source_dir}/src/core/support/thd_internal.h
	${grpc_source_dir}/src/core/support/time_precise.h
	${grpc_source_dir}/src/core/census/grpc_filter.h
	${grpc_source_dir}/src/core/channel/channel_args.h
	${grpc_source_dir}/src/core/channel/channel_stack.h
	${grpc_source_dir}/src/core/channel/client_channel.h
	${grpc_source_dir}/src/core/channel/client_uchannel.h
	${grpc_source_dir}/src/core/channel/compress_filter.h
	${grpc_source_dir}/src/core/channel/connected_channel.h
	${grpc_source_dir}/src/core/channel/context.h
	${grpc_source_dir}/src/core/channel/http_client_filter.h
	${grpc_source_dir}/src/core/channel/http_server_filter.h
	${grpc_source_dir}/src/core/channel/subchannel_call_holder.h
	${grpc_source_dir}/src/core/client_config/client_config.h
	${grpc_source_dir}/src/core/client_config/connector.h
	${grpc_source_dir}/src/core/client_config/initial_connect_string.h
	${grpc_source_dir}/src/core/client_config/lb_policies/pick_first.h
	${grpc_source_dir}/src/core/client_config/lb_policies/round_robin.h
	${grpc_source_dir}/src/core/client_config/lb_policy.h
	${grpc_source_dir}/src/core/client_config/lb_policy_factory.h
	${grpc_source_dir}/src/core/client_config/lb_policy_registry.h
	${grpc_source_dir}/src/core/client_config/resolver.h
	${grpc_source_dir}/src/core/client_config/resolver_factory.h
	${grpc_source_dir}/src/core/client_config/resolver_registry.h
	${grpc_source_dir}/src/core/client_config/resolvers/dns_resolver.h
	${grpc_source_dir}/src/core/client_config/resolvers/sockaddr_resolver.h
	${grpc_source_dir}/src/core/client_config/subchannel.h
	${grpc_source_dir}/src/core/client_config/subchannel_factory.h
	${grpc_source_dir}/src/core/client_config/uri_parser.h
	${grpc_source_dir}/src/core/compression/algorithm_metadata.h
	${grpc_source_dir}/src/core/compression/message_compress.h
	${grpc_source_dir}/src/core/debug/trace.h
	${grpc_source_dir}/src/core/httpcli/format_request.h
	${grpc_source_dir}/src/core/httpcli/httpcli.h
	${grpc_source_dir}/src/core/httpcli/parser.h
	${grpc_source_dir}/src/core/iomgr/closure.h
	${grpc_source_dir}/src/core/iomgr/endpoint.h
	${grpc_source_dir}/src/core/iomgr/endpoint_pair.h
	${grpc_source_dir}/src/core/iomgr/exec_ctx.h
	${grpc_source_dir}/src/core/iomgr/executor.h
	${grpc_source_dir}/src/core/iomgr/fd_posix.h
	${grpc_source_dir}/src/core/iomgr/iocp_windows.h
	${grpc_source_dir}/src/core/iomgr/iomgr.h
	${grpc_source_dir}/src/core/iomgr/iomgr_internal.h
	${grpc_source_dir}/src/core/iomgr/iomgr_posix.h
	${grpc_source_dir}/src/core/iomgr/pollset.h
	${grpc_source_dir}/src/core/iomgr/pollset_posix.h
	${grpc_source_dir}/src/core/iomgr/pollset_set.h
	${grpc_source_dir}/src/core/iomgr/pollset_set_posix.h
	${grpc_source_dir}/src/core/iomgr/pollset_set_windows.h
	${grpc_source_dir}/src/core/iomgr/pollset_windows.h
	${grpc_source_dir}/src/core/iomgr/resolve_address.h
	${grpc_source_dir}/src/core/iomgr/sockaddr.h
	${grpc_source_dir}/src/core/iomgr/sockaddr_posix.h
	${grpc_source_dir}/src/core/iomgr/sockaddr_utils.h
	${grpc_source_dir}/src/core/iomgr/sockaddr_win32.h
	${grpc_source_dir}/src/core/iomgr/socket_utils_posix.h
	${grpc_source_dir}/src/core/iomgr/socket_windows.h
	${grpc_source_dir}/src/core/iomgr/tcp_client.h
	${grpc_source_dir}/src/core/iomgr/tcp_posix.h
	${grpc_source_dir}/src/core/iomgr/tcp_server.h
	${grpc_source_dir}/src/core/iomgr/tcp_windows.h
	${grpc_source_dir}/src/core/iomgr/time_averaged_stats.h
	${grpc_source_dir}/src/core/iomgr/timer.h
	${grpc_source_dir}/src/core/iomgr/timer_heap.h
	${grpc_source_dir}/src/core/iomgr/timer_internal.h
	${grpc_source_dir}/src/core/iomgr/udp_server.h
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_pipe.h
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_posix.h
	${grpc_source_dir}/src/core/iomgr/workqueue.h
	${grpc_source_dir}/src/core/iomgr/workqueue_posix.h
	${grpc_source_dir}/src/core/iomgr/workqueue_windows.h
	${grpc_source_dir}/src/core/json/json.h
	${grpc_source_dir}/src/core/json/json_common.h
	${grpc_source_dir}/src/core/json/json_reader.h
	${grpc_source_dir}/src/core/json/json_writer.h
	${grpc_source_dir}/src/core/statistics/census_interface.h
	${grpc_source_dir}/src/core/statistics/census_rpc_stats.h
	${grpc_source_dir}/src/core/surface/api_trace.h
	${grpc_source_dir}/src/core/surface/call.h
	${grpc_source_dir}/src/core/surface/call_test_only.h
	${grpc_source_dir}/src/core/surface/channel.h
	${grpc_source_dir}/src/core/surface/completion_queue.h
	${grpc_source_dir}/src/core/surface/event_string.h
	${grpc_source_dir}/src/core/surface/init.h
	${grpc_source_dir}/src/core/surface/server.h
	${grpc_source_dir}/src/core/surface/surface_trace.h
	${grpc_source_dir}/src/core/transport/byte_stream.h
	${grpc_source_dir}/src/core/transport/chttp2/alpn.h
	${grpc_source_dir}/src/core/transport/chttp2/bin_encoder.h
	${grpc_source_dir}/src/core/transport/chttp2/frame.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_data.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_goaway.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_ping.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_rst_stream.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_settings.h
	${grpc_source_dir}/src/core/transport/chttp2/frame_window_update.h
	${grpc_source_dir}/src/core/transport/chttp2/hpack_encoder.h
	${grpc_source_dir}/src/core/transport/chttp2/hpack_parser.h
	${grpc_source_dir}/src/core/transport/chttp2/hpack_table.h
	${grpc_source_dir}/src/core/transport/chttp2/http2_errors.h
	${grpc_source_dir}/src/core/transport/chttp2/huffsyms.h
	${grpc_source_dir}/src/core/transport/chttp2/incoming_metadata.h
	${grpc_source_dir}/src/core/transport/chttp2/internal.h
	${grpc_source_dir}/src/core/transport/chttp2/status_conversion.h
	${grpc_source_dir}/src/core/transport/chttp2/stream_map.h
	${grpc_source_dir}/src/core/transport/chttp2/timeout_encoding.h
	${grpc_source_dir}/src/core/transport/chttp2/varint.h
	${grpc_source_dir}/src/core/transport/chttp2_transport.h
	${grpc_source_dir}/src/core/transport/connectivity_state.h
	${grpc_source_dir}/src/core/transport/metadata.h
	${grpc_source_dir}/src/core/transport/metadata_batch.h
	${grpc_source_dir}/src/core/transport/static_metadata.h
	${grpc_source_dir}/src/core/transport/transport.h
	${grpc_source_dir}/src/core/transport/transport_impl.h
	${grpc_source_dir}/src/core/census/aggregation.h
	${grpc_source_dir}/src/core/census/rpc_metric_id.h
	${grpc_source_dir}/src/core/surface/init_unsecure.c
	${grpc_source_dir}/src/core/profiling/basic_timers.c
	${grpc_source_dir}/src/core/profiling/stap_timers.c
	${grpc_source_dir}/src/core/support/alloc.c
	${grpc_source_dir}/src/core/support/avl.c
	${grpc_source_dir}/src/core/support/cmdline.c
	${grpc_source_dir}/src/core/support/cpu_iphone.c
	${grpc_source_dir}/src/core/support/cpu_linux.c
	${grpc_source_dir}/src/core/support/cpu_posix.c
	${grpc_source_dir}/src/core/support/cpu_windows.c
	${grpc_source_dir}/src/core/support/env_linux.c
	${grpc_source_dir}/src/core/support/env_posix.c
	${grpc_source_dir}/src/core/support/env_win32.c
	${grpc_source_dir}/src/core/support/file.c
	${grpc_source_dir}/src/core/support/file_posix.c
	${grpc_source_dir}/src/core/support/file_win32.c
	${grpc_source_dir}/src/core/support/histogram.c
	${grpc_source_dir}/src/core/support/host_port.c
	${grpc_source_dir}/src/core/support/log.c
	${grpc_source_dir}/src/core/support/log_android.c
	${grpc_source_dir}/src/core/support/log_linux.c
	${grpc_source_dir}/src/core/support/log_posix.c
	${grpc_source_dir}/src/core/support/log_win32.c
	${grpc_source_dir}/src/core/support/murmur_hash.c
	${grpc_source_dir}/src/core/support/slice.c
	${grpc_source_dir}/src/core/support/slice_buffer.c
	${grpc_source_dir}/src/core/support/stack_lockfree.c
	${grpc_source_dir}/src/core/support/string.c
	${grpc_source_dir}/src/core/support/string_posix.c
	${grpc_source_dir}/src/core/support/string_win32.c
	${grpc_source_dir}/src/core/support/subprocess_posix.c
	${grpc_source_dir}/src/core/support/subprocess_windows.c
	${grpc_source_dir}/src/core/support/sync.c
	${grpc_source_dir}/src/core/support/sync_posix.c
	${grpc_source_dir}/src/core/support/sync_win32.c
	${grpc_source_dir}/src/core/support/thd.c
	${grpc_source_dir}/src/core/support/thd_posix.c
	${grpc_source_dir}/src/core/support/thd_win32.c
	${grpc_source_dir}/src/core/support/time.c
	${grpc_source_dir}/src/core/support/time_posix.c
	${grpc_source_dir}/src/core/support/time_precise.c
	${grpc_source_dir}/src/core/support/time_win32.c
	${grpc_source_dir}/src/core/support/tls_pthread.c
	${grpc_source_dir}/src/core/support/wrap_memcpy.c
	${grpc_source_dir}/src/core/census/grpc_context.c
	${grpc_source_dir}/src/core/census/grpc_filter.c
	${grpc_source_dir}/src/core/channel/channel_args.c
	${grpc_source_dir}/src/core/channel/channel_stack.c
	${grpc_source_dir}/src/core/channel/client_channel.c
	${grpc_source_dir}/src/core/channel/client_uchannel.c
	${grpc_source_dir}/src/core/channel/compress_filter.c
	${grpc_source_dir}/src/core/channel/connected_channel.c
	${grpc_source_dir}/src/core/channel/http_client_filter.c
	${grpc_source_dir}/src/core/channel/http_server_filter.c
	${grpc_source_dir}/src/core/channel/subchannel_call_holder.c
	${grpc_source_dir}/src/core/client_config/client_config.c
	${grpc_source_dir}/src/core/client_config/connector.c
	${grpc_source_dir}/src/core/client_config/default_initial_connect_string.c
	${grpc_source_dir}/src/core/client_config/initial_connect_string.c
	${grpc_source_dir}/src/core/client_config/lb_policies/pick_first.c
	${grpc_source_dir}/src/core/client_config/lb_policies/round_robin.c
	${grpc_source_dir}/src/core/client_config/lb_policy.c
	${grpc_source_dir}/src/core/client_config/lb_policy_factory.c
	${grpc_source_dir}/src/core/client_config/lb_policy_registry.c
	${grpc_source_dir}/src/core/client_config/resolver.c
	${grpc_source_dir}/src/core/client_config/resolver_factory.c
	${grpc_source_dir}/src/core/client_config/resolver_registry.c
	${grpc_source_dir}/src/core/client_config/resolvers/dns_resolver.c
	${grpc_source_dir}/src/core/client_config/resolvers/sockaddr_resolver.c
	${grpc_source_dir}/src/core/client_config/subchannel.c
	${grpc_source_dir}/src/core/client_config/subchannel_factory.c
	${grpc_source_dir}/src/core/client_config/uri_parser.c
	${grpc_source_dir}/src/core/compression/algorithm.c
	${grpc_source_dir}/src/core/compression/message_compress.c
	${grpc_source_dir}/src/core/debug/trace.c
	${grpc_source_dir}/src/core/httpcli/format_request.c
	${grpc_source_dir}/src/core/httpcli/httpcli.c
	${grpc_source_dir}/src/core/httpcli/parser.c
	${grpc_source_dir}/src/core/iomgr/closure.c
	${grpc_source_dir}/src/core/iomgr/endpoint.c
	${grpc_source_dir}/src/core/iomgr/endpoint_pair_posix.c
	${grpc_source_dir}/src/core/iomgr/endpoint_pair_windows.c
	${grpc_source_dir}/src/core/iomgr/exec_ctx.c
	${grpc_source_dir}/src/core/iomgr/executor.c
	${grpc_source_dir}/src/core/iomgr/fd_posix.c
	${grpc_source_dir}/src/core/iomgr/iocp_windows.c
	${grpc_source_dir}/src/core/iomgr/iomgr.c
	${grpc_source_dir}/src/core/iomgr/iomgr_posix.c
	${grpc_source_dir}/src/core/iomgr/iomgr_windows.c
	${grpc_source_dir}/src/core/iomgr/pollset_multipoller_with_epoll.c
	${grpc_source_dir}/src/core/iomgr/pollset_multipoller_with_poll_posix.c
	${grpc_source_dir}/src/core/iomgr/pollset_posix.c
	${grpc_source_dir}/src/core/iomgr/pollset_set_posix.c
	${grpc_source_dir}/src/core/iomgr/pollset_set_windows.c
	${grpc_source_dir}/src/core/iomgr/pollset_windows.c
	${grpc_source_dir}/src/core/iomgr/resolve_address_posix.c
	${grpc_source_dir}/src/core/iomgr/resolve_address_windows.c
	${grpc_source_dir}/src/core/iomgr/sockaddr_utils.c
	${grpc_source_dir}/src/core/iomgr/socket_utils_common_posix.c
	${grpc_source_dir}/src/core/iomgr/socket_utils_linux.c
	${grpc_source_dir}/src/core/iomgr/socket_utils_posix.c
	${grpc_source_dir}/src/core/iomgr/socket_windows.c
	${grpc_source_dir}/src/core/iomgr/tcp_client_posix.c
	${grpc_source_dir}/src/core/iomgr/tcp_client_windows.c
	${grpc_source_dir}/src/core/iomgr/tcp_posix.c
	${grpc_source_dir}/src/core/iomgr/tcp_server_posix.c
	${grpc_source_dir}/src/core/iomgr/tcp_server_windows.c
	${grpc_source_dir}/src/core/iomgr/tcp_windows.c
	${grpc_source_dir}/src/core/iomgr/time_averaged_stats.c
	${grpc_source_dir}/src/core/iomgr/timer.c
	${grpc_source_dir}/src/core/iomgr/timer_heap.c
	${grpc_source_dir}/src/core/iomgr/udp_server.c
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_eventfd.c
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_nospecial.c
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_pipe.c
	${grpc_source_dir}/src/core/iomgr/wakeup_fd_posix.c
	${grpc_source_dir}/src/core/iomgr/workqueue_posix.c
	${grpc_source_dir}/src/core/iomgr/workqueue_windows.c
	${grpc_source_dir}/src/core/json/json.c
	${grpc_source_dir}/src/core/json/json_reader.c
	${grpc_source_dir}/src/core/json/json_string.c
	${grpc_source_dir}/src/core/json/json_writer.c
	${grpc_source_dir}/src/core/surface/alarm.c
	${grpc_source_dir}/src/core/surface/api_trace.c
	${grpc_source_dir}/src/core/surface/byte_buffer.c
	${grpc_source_dir}/src/core/surface/byte_buffer_reader.c
	${grpc_source_dir}/src/core/surface/call.c
	${grpc_source_dir}/src/core/surface/call_details.c
	${grpc_source_dir}/src/core/surface/call_log_batch.c
	${grpc_source_dir}/src/core/surface/channel.c
	${grpc_source_dir}/src/core/surface/channel_connectivity.c
	${grpc_source_dir}/src/core/surface/channel_create.c
	${grpc_source_dir}/src/core/surface/channel_ping.c
	${grpc_source_dir}/src/core/surface/completion_queue.c
	${grpc_source_dir}/src/core/surface/event_string.c
	${grpc_source_dir}/src/core/surface/init.c
	${grpc_source_dir}/src/core/surface/lame_client.c
	${grpc_source_dir}/src/core/surface/metadata_array.c
	${grpc_source_dir}/src/core/surface/server.c
	${grpc_source_dir}/src/core/surface/server_chttp2.c
	${grpc_source_dir}/src/core/surface/server_create.c
	${grpc_source_dir}/src/core/surface/validate_metadata.c
	${grpc_source_dir}/src/core/surface/version.c
	${grpc_source_dir}/src/core/transport/byte_stream.c
	${grpc_source_dir}/src/core/transport/chttp2/alpn.c
	${grpc_source_dir}/src/core/transport/chttp2/bin_encoder.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_data.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_goaway.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_ping.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_rst_stream.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_settings.c
	${grpc_source_dir}/src/core/transport/chttp2/frame_window_update.c
	${grpc_source_dir}/src/core/transport/chttp2/hpack_encoder.c
	${grpc_source_dir}/src/core/transport/chttp2/hpack_parser.c
	${grpc_source_dir}/src/core/transport/chttp2/hpack_table.c
	${grpc_source_dir}/src/core/transport/chttp2/huffsyms.c
	${grpc_source_dir}/src/core/transport/chttp2/incoming_metadata.c
	${grpc_source_dir}/src/core/transport/chttp2/parsing.c
	${grpc_source_dir}/src/core/transport/chttp2/status_conversion.c
	${grpc_source_dir}/src/core/transport/chttp2/stream_lists.c
	${grpc_source_dir}/src/core/transport/chttp2/stream_map.c
	${grpc_source_dir}/src/core/transport/chttp2/timeout_encoding.c
	${grpc_source_dir}/src/core/transport/chttp2/varint.c
	${grpc_source_dir}/src/core/transport/chttp2/writing.c
	${grpc_source_dir}/src/core/transport/chttp2_transport.c
	${grpc_source_dir}/src/core/transport/connectivity_state.c
	${grpc_source_dir}/src/core/transport/metadata.c
	${grpc_source_dir}/src/core/transport/metadata_batch.c
	${grpc_source_dir}/src/core/transport/static_metadata.c
	${grpc_source_dir}/src/core/transport/transport.c
	${grpc_source_dir}/src/core/transport/transport_op_string.c
	${grpc_source_dir}/src/core/census/context.c
	${grpc_source_dir}/src/core/census/initialize.c
	${grpc_source_dir}/src/core/census/operation.c
	${grpc_source_dir}/src/core/census/placeholders.c
	${grpc_source_dir}/src/core/census/tracing.c
)

set(libgrpc_unsecure_header_files
	${grpc_source_dir}/include/grpc/support/alloc.h
	${grpc_source_dir}/include/grpc/support/atm.h
	${grpc_source_dir}/include/grpc/support/atm_gcc_atomic.h
	${grpc_source_dir}/include/grpc/support/atm_gcc_sync.h
	${grpc_source_dir}/include/grpc/support/atm_win32.h
	${grpc_source_dir}/include/grpc/support/avl.h
	${grpc_source_dir}/include/grpc/support/cmdline.h
	${grpc_source_dir}/include/grpc/support/cpu.h
	${grpc_source_dir}/include/grpc/support/histogram.h
	${grpc_source_dir}/include/grpc/support/host_port.h
	${grpc_source_dir}/include/grpc/support/log.h
	${grpc_source_dir}/include/grpc/support/log_win32.h
	${grpc_source_dir}/include/grpc/support/port_platform.h
	${grpc_source_dir}/include/grpc/support/slice.h
	${grpc_source_dir}/include/grpc/support/slice_buffer.h
	${grpc_source_dir}/include/grpc/support/string_util.h
	${grpc_source_dir}/include/grpc/support/subprocess.h
	${grpc_source_dir}/include/grpc/support/sync.h
	${grpc_source_dir}/include/grpc/support/sync_generic.h
	${grpc_source_dir}/include/grpc/support/sync_posix.h
	${grpc_source_dir}/include/grpc/support/sync_win32.h
	${grpc_source_dir}/include/grpc/support/thd.h
	${grpc_source_dir}/include/grpc/support/time.h
	${grpc_source_dir}/include/grpc/support/tls.h
	${grpc_source_dir}/include/grpc/support/tls_gcc.h
	${grpc_source_dir}/include/grpc/support/tls_msvc.h
	${grpc_source_dir}/include/grpc/support/tls_pthread.h
	${grpc_source_dir}/include/grpc/support/useful.h
	${grpc_source_dir}/include/grpc/impl/codegen/alloc.h
	${grpc_source_dir}/include/grpc/impl/codegen/atm.h
	${grpc_source_dir}/include/grpc/impl/codegen/atm_gcc_atomic.h
	${grpc_source_dir}/include/grpc/impl/codegen/atm_gcc_sync.h
	${grpc_source_dir}/include/grpc/impl/codegen/atm_win32.h
	${grpc_source_dir}/include/grpc/impl/codegen/byte_buffer.h
	${grpc_source_dir}/include/grpc/impl/codegen/compression_types.h
	${grpc_source_dir}/include/grpc/impl/codegen/connectivity_state.h
	${grpc_source_dir}/include/grpc/impl/codegen/grpc_types.h
	${grpc_source_dir}/include/grpc/impl/codegen/log.h
	${grpc_source_dir}/include/grpc/impl/codegen/port_platform.h
	${grpc_source_dir}/include/grpc/impl/codegen/propagation_bits.h
	${grpc_source_dir}/include/grpc/impl/codegen/slice.h
	${grpc_source_dir}/include/grpc/impl/codegen/slice_buffer.h
	${grpc_source_dir}/include/grpc/impl/codegen/status.h
	${grpc_source_dir}/include/grpc/impl/codegen/sync.h
	${grpc_source_dir}/include/grpc/impl/codegen/sync_generic.h
	${grpc_source_dir}/include/grpc/impl/codegen/sync_posix.h
	${grpc_source_dir}/include/grpc/impl/codegen/sync_win32.h
	${grpc_source_dir}/include/grpc/impl/codegen/time.h
	${grpc_source_dir}/include/grpc/byte_buffer.h
	${grpc_source_dir}/include/grpc/byte_buffer_reader.h
	${grpc_source_dir}/include/grpc/compression.h
	${grpc_source_dir}/include/grpc/grpc.h
	${grpc_source_dir}/include/grpc/status.h
	${grpc_source_dir}/include/grpc/census.h
)
